version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: otterflow-backend/Dockerfile.backend
    volumes:
      - ./otterflow-backend:/app
    env_file:
      - ./otterflow-backend/.env.backend
    networks:
      - app-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: otterflow-frontend/Dockerfile.frontend
    volumes:
      - ./otterflow-frontend:/app
    env_file:
      - ./otterflow-backend/.env.backend
    environment:
      - REACT_APP_BACKEND_URL=https://otterflow.in/api
      - NEXT_PUBLIC_BACKEND_URL=https://otterflow.in/api
    networks:
      - app-network
    command: npm run dev

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgadmin-data:
